
sonar.projectKey=fastapi-app
sonar.projectName=fastapi-app

sonar.host.url=http://localhost:9000
sonar.login=sqp_5d1dfa105ed79c9beed0ef16415f59c25028012f

sonar.sources=.

sonar.exclusions=venv/**,__pycache__/**
